### ISSUE TITLE
Access Pages

### ISSUE THREAD

**Issue by Colmine** [cs481-ekh/s21-team-blue#1]
As a general user, I need to be able to access my previous information with the device so that I know what tests have been run and what else needs to be tested.

**Acceptance Criteria:**
- [x] Given I am on a PC that _has never_ run tests with PiRate before, when I go to the PiRate homepage, then I am able to click a button that redirects me to the setup page.
- [x] Given I am on a PC that _has_ run tests with PiRate before, when I upload the file that contains all of my previously-run tests, then I will be able to view all previous tests run on this PC from inside the PiRate website.
- [x] Given I am on a PC that _has_ run tests with PiRate before, when I click the "Settings" link, then I am able to view my Operating System information and change it if necessary.
