### ISSUE TITLE
Testing UI

### ISSUE THREAD

**Issue by Colmine** [cs481-ekh/s21-team-blue#2]
As a general user, I need to have some kind of intuitive interface so that I know what tests I'm running and can see the results of the tests ran.

**Acceptance Criteria:**
- [x] Given I connect the PiRate device to my PC, when I navigate to the PiRate homepage on my PC, then I am able to see a list of all available tests that can be executed.
- [x] Given I I run a test or a set of tests, when I click "View Results", then I am able to see an orderly list of the results of all tests, with detailed information about any warnings or failed tests.
- [x] Given I have previously run a test or a set of tests, when I navigate to the "Test History" page, then I am able to see all of the tests I have previously run on this PC.
- [x] Given I have a question about one of the tests, when I click on the test, then I am shown more detailed information about the test and what it does.
- [x] Given I click the checkbox next to one or more tests, when I click "Run", all of the tests I selected will be executed.
