### ISSUE TITLE
Testing Suite

### ISSUE THREAD

**Issue by Colmine** [cs481-ekh/s21-team-blue#3]
As a developer or security engineer, I need to know what tests are available to run so that I know what tests can be run from the device and if I need to create, or run, my own edge-case tests.

**Acceptance Criteria:**
- [x] Given TBDContext, when TBDTrigger, then TBDSomeResult
- [x] Given TBDContext, when TBDTrigger, then TBDSomeResult
- [ ] Given TBDContext, when TBDTrigger, then TBDSomeResult
- [ ] Given TBDContext, when TBDTrigger, then TBDSomeResult
- [ ] Given TBDContext, when TBDTrigger, then TBDSomeResult
