### ISSUE TITLE
Backend Integration

### ISSUE THREAD

**Issue by Colmine** [cs481-ekh/s21-team-blue#4]
As a developer, I need to know what API is being used to communicate with the Pi and the Client machine so that I know of any potential weak points in the system's infrastructure/communication methods.

**Acceptance Criteria:**
- [x] Given the product, when I connect the Pi to my PC, then I should get some kind of webpage to pop-up that can let me communicate between the Pi and PC.
- [x] Given a login page, when I connect the Pi to my PC, then I should be able to login and get a list of tests that are already on the Pi from the webpage.
- [x] Given a successful connection and login page, when I have the Pi connected to my PC, then I should be able to click on the tests I want to run and they will execute the proper tests from the Pi.
- [x] Given a successful run of tests, when the Pi is connected to my PC, then I should be able to get the results of the test(s) from the Pi and not have anything break in the communication between the Pi and PC and can run another test immediately.
